### PR TITLE
Updated all of web auth

### PR DESCRIPTION
**Pull request by COMTOP1**
I have spent a while fixing a lot of things to do with web auth, quite a lot of changes but looks better now and fixed some of the old problems, it is a complete rebuild and fully manages users and permissions.

### CODE REVIEW

**Comment by COMTOP1** [comment]
Jenkins fails simply of the branch name, it doesn't like the slash apparently

**Comment by markspolakovs** [comment]
> Jenkins fails simply of the branch name, it doesn't like the slash apparently

Fixed on master and merged into this branch, hopefully that's happier now

**Comment by markspolakovs** [comment]
Summarising Slack discussion: this PR has 94 commits with +9,700/-1,700 lines, which is really difficult to review (even if I exclude all the template changes, there's still 5,769 lines changed in `.go` files, which is quite a lot).

@COMTOP1 could you try to break this apart into smaller PRs - ideally each one would be reviewable in isolation (i.e. it passes CI, merges cleanly into its parent, and is generally a group of related changes), that'd make reviewing this a lot easier. Thanks!

**Comment by COMTOP1** [comment]
I'll try and break it up

**Pull request closed without merging**
